Модуль наполнения базы данными из json файлов, и создание админа.
buylist/backend pull request #6
Opened 2019-05-11 09:32 UTC by gorlovjob

Модуль наполнения базы данными из json файлов, и создание суперпользователя.
mainapp\management\commands\fill_db.py - сам модуль.
mainapp\json\ - json файлы:
buyers.json - список пользователей.
categories.json - список категорий товаров.
items.json - список товаров.

Локально протестировано.
Запуск из командной строки: "python manage.py fill_db"

Косяк: если база уже создана, данные попадают в базу с ID не с нуля. Чтобы такого не происходило, нужно ввести настройки в саму базу (не помню какие, поэтому еще не делал).

2019-05-12 02:37 UTC, anoheroku commented on mainapp/management/commands/fill_db.py
> +    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', encoding='utf-8') as infile:
Я бы к пути ещё добавил BASE_DIR из settings

2019-05-12 02:38 UTC, anoheroku commented on mainapp/management/commands/fill_db.py
> +JSON_PATH = 'mainapp/json'
Жёстко задан прямой слэш

2019-05-12 02:39 UTC, anoheroku commented on mainapp/management/commands/fill_db.py
> +        _superuser = Buyer.objects.filter(username='admin').first()
Мы только что всех удалили в строке 22

2019-05-12 02:40 UTC, anoheroku commented on mainapp/management/commands/fill_db.py
> +            Buyer.objects.create_superuser('admin', 'buylist.project@gmail.com', 'y1u2i3o4y1u2i3o4')
Такие данные надо передавать через config.json, чтобы не светить пароль администратора

2019-05-12 02:56 UTC, anoheroku requested changes
Жёстко задан прямой слэш в строке 6
Убрать данные суперпользователя из строки 27, изменить на config.SUPERUSER['username'] и т.п. (конфиг нужно подгрузить из settings)

2019-05-12 05:23 UTC, anoheroku commented on mainapp/management/commands/fill_db.py
> +        Buyer.objects.bulk_create(buyers_objs)
в этом случае пароль не шифруется и залогиниться невозможно

2019-05-17 21:51 UTC, buylist approved these changes

2019-05-17 21:52 UTC, anoheroku approved these changes

2019-05-17 21:52 UTC, merged